require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe AnswerGivensController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # AnswerGiven. As you add validations to AnswerGiven, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AnswerGivensController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all answer_givens as @answer_givens" do
      answer_given = AnswerGiven.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:answer_givens)).to eq([answer_given])
    end
  end

  describe "GET show" do
    it "assigns the requested answer_given as @answer_given" do
      answer_given = AnswerGiven.create! valid_attributes
      get :show, {:id => answer_given.to_param}, valid_session
      expect(assigns(:answer_given)).to eq(answer_given)
    end
  end

  describe "GET new" do
    it "assigns a new answer_given as @answer_given" do
      get :new, {}, valid_session
      expect(assigns(:answer_given)).to be_a_new(AnswerGiven)
    end
  end

  describe "GET edit" do
    it "assigns the requested answer_given as @answer_given" do
      answer_given = AnswerGiven.create! valid_attributes
      get :edit, {:id => answer_given.to_param}, valid_session
      expect(assigns(:answer_given)).to eq(answer_given)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AnswerGiven" do
        expect {
          post :create, {:answer_given => valid_attributes}, valid_session
        }.to change(AnswerGiven, :count).by(1)
      end

      it "assigns a newly created answer_given as @answer_given" do
        post :create, {:answer_given => valid_attributes}, valid_session
        expect(assigns(:answer_given)).to be_a(AnswerGiven)
        expect(assigns(:answer_given)).to be_persisted
      end

      it "redirects to the created answer_given" do
        post :create, {:answer_given => valid_attributes}, valid_session
        expect(response).to redirect_to(AnswerGiven.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved answer_given as @answer_given" do
        post :create, {:answer_given => invalid_attributes}, valid_session
        expect(assigns(:answer_given)).to be_a_new(AnswerGiven)
      end

      it "re-renders the 'new' template" do
        post :create, {:answer_given => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested answer_given" do
        answer_given = AnswerGiven.create! valid_attributes
        put :update, {:id => answer_given.to_param, :answer_given => new_attributes}, valid_session
        answer_given.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested answer_given as @answer_given" do
        answer_given = AnswerGiven.create! valid_attributes
        put :update, {:id => answer_given.to_param, :answer_given => valid_attributes}, valid_session
        expect(assigns(:answer_given)).to eq(answer_given)
      end

      it "redirects to the answer_given" do
        answer_given = AnswerGiven.create! valid_attributes
        put :update, {:id => answer_given.to_param, :answer_given => valid_attributes}, valid_session
        expect(response).to redirect_to(answer_given)
      end
    end

    describe "with invalid params" do
      it "assigns the answer_given as @answer_given" do
        answer_given = AnswerGiven.create! valid_attributes
        put :update, {:id => answer_given.to_param, :answer_given => invalid_attributes}, valid_session
        expect(assigns(:answer_given)).to eq(answer_given)
      end

      it "re-renders the 'edit' template" do
        answer_given = AnswerGiven.create! valid_attributes
        put :update, {:id => answer_given.to_param, :answer_given => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested answer_given" do
      answer_given = AnswerGiven.create! valid_attributes
      expect {
        delete :destroy, {:id => answer_given.to_param}, valid_session
      }.to change(AnswerGiven, :count).by(-1)
    end

    it "redirects to the answer_givens list" do
      answer_given = AnswerGiven.create! valid_attributes
      delete :destroy, {:id => answer_given.to_param}, valid_session
      expect(response).to redirect_to(answer_givens_url)
    end
  end

end
